#!/bin/bash

usage() {
    echo "Usage: $0 -b <build_dir> -n <app_name>"
}

BUILD_DIR_NAME=$1
BUILD_DIR_PATH=../$BUILD_DIR_NAME
APP_NAME=$2
OUTNAME=$APP_NAME.out
PATH_TO_EXECUTABLE=$BUILD_DIR_PATH/$OUTNAME

SDK_DIR=$HOME/dev/ti/am64x/sdk/mcu_plus_sdk_am64x_09_02_01_05/

SYSCFG_DIR=$HOME/dev/ti/sysconfig/sysconfig_1.20.0/
SYSCFG_NODE=$SYSCFG_DIR/nodejs/node
SYSCFG_CLI=$SYSCFG_DIR/dist/cli.js

XIPGEN_CMD=$SDK_DIR/tools/boot/xipGen/xipGen.out
OUTRPRC_CMD="$SYSCFG_NODE $SDK_DIR/tools/boot/out2rprc/elf2rprc.js"
MULTI_CORE_IMAGE_GEN="$SYSCFG_NODE $SDK_DIR/tools/boot/multicoreImageGen/multicoreImageGen.js"
APP_IMAGE_SIGN_CMD=$SDK_DIR/tools/boot/signing/appimage_x509_cert_gen.py

BOOTIMAGE_NAME=$BUILD_DIR_PATH/$APP_NAME.appimage
BOOTIMAGE_NAME_XIP=$BUILD_DIR_PATH/$APP_NAME.appimage_xip
BOOTIMAGE_NAME_SIGNED=$BUILD_DIR_PATH/$APP_NAME.appimage.signed
BOOTIMAGE_RPRC_NAME=$APP_NAME.rprc
BOOTIMAGE_RPRC_NAME_XIP=$BUILD_DIR_PATH/$APP_NAME.rprc_xip
BOOTIMAGE_RPRC_NAME_TMP=$BUILD_DIR_PATH/$APP_NAME.rprc_tmp
BOOTIMAGE_NAME_HS=$BUILD_DIR_PATH/$APP_NAME.appimage.hs
BOOTIMAGE_NAME_HS_FS=$BUILD_DIR_PATH/$APP_NAME.appimage.hs_fs

BOOTIMAGE_CORE_ID_a53ss0_0=0
BOOTIMAGE_CORE_ID_r5fss0_0=4
BOOTIMAGE_CORE_ID_r5fss0_1=5
BOOTIMAGE_CORE_ID_r5fss1_0=6
BOOTIMAGE_CORE_ID_r5fss1_1=7
BOOTIMAGE_CORE_ID_m4fss0_0=14
SBL_RUN_ADDRESS=0x70000000
SBL_DEV_ID=55

MULTI_CORE_IMAGE_PARAMS=$BOOTIMAGE_RPRC_NAME@$BOOTIMAGE_CORE_ID_r5fss0_0
MULTI_CORE_IMAGE_PARAMS_XIP=$BOOTIMAGE_RPRC_NAME_XIP@$BOOTIMAGE_CORE_ID_r5fss0_0

APP_SIGNING_KEY=$SDK_DIR/tools/boot/signing/app_degenerateKey.pem

BOOTIMAGE_TEMP_OUT_FILE=$BUILD_DIR_PATH/temp_stdout_release.txt

$OUTRPRC_CMD $PATH_TO_EXECUTABLE >> $BOOTIMAGE_TEMP_OUT_FILE
cp $BOOTIMAGE_RPRC_NAME $BOOTIMAGE_RPRC_NAME_TMP
$XIPGEN_CMD -i $BOOTIMAGE_RPRC_NAME_TMP -o $BOOTIMAGE_RPRC_NAME -x $BOOTIMAGE_RPRC_NAME_XIP --flash-start-addr 0x60000000 -v > $BOOTIMAGE_TEMP_OUT_FILE
$MULTI_CORE_IMAGE_GEN --devID $SBL_DEV_ID --out $BOOTIMAGE_NAME $MULTI_CORE_IMAGE_PARAMS >> $BOOTIMAGE_TEMP_OUT_FILE
$MULTI_CORE_IMAGE_GEN --devID $SBL_DEV_ID --out $BOOTIMAGE_NAME_XIP $MULTI_CORE_IMAGE_PARAMS_XIP >> $BOOTIMAGE_TEMP_OUT_FILE
rm $BOOTIMAGE_RPRC_NAME_TMP
rm $BOOTIMAGE_TEMP_OUT_FILE
rm $BOOTIMAGE_RPRC_NAME

python $APP_IMAGE_SIGN_CMD --bin $BOOTIMAGE_NAME --authtype 1 --key $APP_SIGNING_KEY --output $BOOTIMAGE_NAME_HS_FS

